import fs from 'node:fs/promises';
import path from 'node:path';
import {Workbook,SpreadsheetFile} from '@oai/artifact-tool';
const ROOT=path.resolve(import.meta.dirname,'..'),OUT=path.join(ROOT,'outputs');
const all=JSON.parse(await fs.readFile(path.join(OUT,'analysis.json'),'utf8'));
const USD='$#,##0.0"M";($#,##0.0"M");"–"',PCT='0.0%;(0.0%);"–"';
const fmt=u=>u==='decimal'?PCT:u==='percent'?'0.0\"%\"':u==='million shares'?'#,##0.0':u==='USD/share'?'$0.00':USD;
const title=s=>s==='core_income_per_diluted_share_proxy'?'Core income / share (proxy)':s.replaceAll('_',' ').replace(/\b\w/g,x=>x.toUpperCase());
const col=n=>{let s='';for(n++;n;n=Math.floor((n-1)/26))s=String.fromCharCode(65+(n-1)%26)+s;return s};
for(const [company,d] of Object.entries(all)){
 const wb=Workbook.create(),brand=company==='PG'?'#003DA5':'#C8102E';
 const names=['Summary','Financial Health','Scenario Model','Assumptions','Forecast Comparison','Variance Drivers','Research Changes','Market Evidence','Historical Financials','Sources and Checks'];
 const sh=Object.fromEntries(names.map(n=>[n,wb.worksheets.add(n)]));
 for(const s of Object.values(sh)){s.showGridLines=false;s.getRange('A1:Q90').format.font={name:'Arial',size:12};s.getRange('A1:B90').format.columnWidth=3;s.getRange('C1:C90').format.columnWidth=36;s.getRange('D1:Q90').format.columnWidth=18;s.getRange('A1:Q90').format.rowHeight=23;s.getRange('A1:Q90').format.verticalAlignment='center';}
 function heading(s,text){s.getRange('C2').values=[[text]];s.getRange('C2').format.font={name:'Arial',size:18,bold:true,color:brand};s.getRange('C3:J3').format.borders={bottom:{style:'thin',color:brand}};}
 function header(s,range,values){s.getRange(range).values=[values];s.getRange(range).format={fill:brand,font:{name:'Arial',size:12,bold:true,color:'#FFFFFF'},rowHeight:40,wrapText:true};}
 function formula(s,cell,f){s.getRange(cell).formulas=[[f]];s.getRange(cell).format.font={name:'Arial',size:12,color:f.includes('!')?'#16713E':'#111111'};}
 function money(s,range){s.getRange(range).setNumberFormat(USD);}
 function signs(s,range){const r=s.getRange(range);r.conditionalFormats.add('cellIs',{operator:'lessThan',formula:0,format:{font:{color:'#BD2939'}}});r.conditionalFormats.add('cellIs',{operator:'greaterThan',formula:0,format:{font:{color:'#16713E'}}});}
 const profit=company==='PG'?'net_income_attributable':'core_income',revenue=company==='PG'?'net_sales':'net_earned_premiums';
 const driverNames=Object.keys(d.forecasts[0].drivers),driverCol=Object.fromEntries(driverNames.map((n,i)=>[n,col(i+3)]));
 const a=sh.Assumptions;heading(a,`${company} | Editable scenario assumptions`);a.tabColor=brand;
 a.getRange('C4').values=[['Case selected:']];a.getRange('D4').values=[[d.forecasts[10].label+' · base']];a.getRange('D4:H4').format.columnWidth=19;
 const cases=d.forecasts.map(f=>`${f.label} · ${f.case}`);a.getRange('D4').dataValidation={rule:{type:'list',formula1:'$C$24:$C$35'}};a.getRange('D4').format.fill='#FFF2CC';a.getRange('D4').format.font.color='#0000FF';
 a.getRange('C6').values=[['Driver']];a.getRange('D6').values=[['Active selection']];a.getRange('F6').values=[['Model definition']];
 const active={};
 for(let i=0;i<driverNames.length;i++){
  const n=driverNames[i],r=7+i;active[n]=`'Assumptions'!D${r}`;a.getRange(`C${r}`).values=[[title(n)]];
  formula(a,`D${r}`,`=INDEX(${driverCol[n]}24:${driverCol[n]}35,MATCH($D$4,$C$24:$C$35,0))`);
  const info=d.runs.mid_market.assumptions.find(x=>x.driver===n);a.getRange(`D${r}`).setNumberFormat(fmt(info.unit));
  a.getRange(`F${r}`).values=[[info.unit==='decimal'?'Decimal ratio; 1% = 0.01':info.unit]];
 }
 a.getRange('C19').values=[['Blue numbers below are editable. Original forecasts remain fixed on Forecast Comparison.']];
 header(a,`C23:${col(driverNames.length+2)}23`,['Scenario',...driverNames.map(title)]);
 a.getRange(`C24:${col(driverNames.length+2)}35`).values=d.forecasts.map((f,i)=>[cases[i],...driverNames.map(n=>f.drivers[n])]);
 a.getRange(`D24:${col(driverNames.length+2)}35`).format.font.color='#0000FF';
 for(let i=0;i<driverNames.length;i++){const info=d.runs.mid_market.assumptions.find(x=>x.driver===driverNames[i]);a.getRange(`${col(i+3)}24:${col(i+3)}35`).setNumberFormat(fmt(info.unit));}
 a.getRange('C23:C35').format.columnWidth=40;a.getRange('D23:O23').format.wrapText=true;a.getRange('D23:O23').format.rowHeight=48;
 const h=sh['Historical Financials'];heading(h,`${company} | Historical financial statements`);h.tabColor='#DFC9A3';
 const periods=[...new Set(d.history.map(r=>r.calendar_quarter))].sort();
 const metrics=[...new Set(d.history.map(r=>r.metric))];header(h,`C5:${col(periods.length+2)}5`,['Metric',...periods.map(p=>company==='PG'?d.history.find(r=>r.calendar_quarter===p).fiscal_period:p)]);
 const histRow={};metrics.forEach((m,i)=>{const r=i+6;histRow[m]=r;h.getRange(`C${r}`).values=[[title(m)]];periods.forEach((p,j)=>{const x=d.history.find(x=>x.metric===m&&x.calendar_quarter===p);if(x)h.getRange(`${col(j+3)}${r}`).values=[[x.value]];});h.getRange(`D${r}:${col(periods.length+2)}${r}`).setNumberFormat(fmt(d.history.find(x=>x.metric===m).unit));});
 h.freezePanes.freezeRows(5);h.getRange(`C6:C${metrics.length+5}`).format.columnWidth=43;
 const model=sh['Scenario Model'];heading(model,`${company} | One live calculation`);model.tabColor=brand;model.getRange('C4').values=[['Case selected:']];formula(model,'D4',"='Assumptions'!D4");
 const bcol=col(3+periods.indexOf('2025Q2'));const href=m=>`'Historical Financials'!${bcol}${histRow[m]}`;
 header(model,'C6:E6',['Calculation','Selected case','Actual Apr–Jun 2026']);
 let defs;
 const dr=n=>active[n];
 if(company==='PG')defs=[['net_sales',`=${href('net_sales')}*(1+${dr('sales_growth')})`],['gross_profit',`=D7*${dr('gross_margin')}`],['sga',`=D7*${dr('sga_ratio')}`],['operating_income','=D8-D9'],['pretax_income',`=D10+${dr('net_nonoperating_income')}`],['income_taxes',`=D11*${dr('effective_tax_rate')}`],['net_income','=D11-D12'],['net_income_attributable',`=D13-${dr('noncontrolling_income')}`],['diluted_eps',`=D14/${dr('diluted_shares')}`],['operating_cash_flow',`=D13*${dr('ocf_to_net_income')}`],['capital_expenditures',`=D7*${dr('capex_ratio')}`],['free_cash_flow','=D16-D17']];
 else defs=[['net_earned_premiums',`=${href('net_earned_premiums')}*(1+${dr('earned_premium_growth')})`],['net_written_premiums',`=${href('net_written_premiums')}*(1+${dr('written_premium_growth')})`],['basis_adjustment',`=${href('underwriting_gain')}-${href('favorable_prior_year_development')}-${href('catastrophe_losses_signed')}-${href('net_earned_premiums')}*(1-${href('underlying_combined_ratio')}/100)`],['underlying_underwriting_gain',`=D7*(1-${dr('underlying_combined_ratio')})+D9`],['underwriting_gain',`=D10-${dr('catastrophe_losses')}+${dr('favorable_reserve_development')}`],['investment_income_pretax',`=${dr('investment_income')}`],['core_pretax_income',`=D11+D12+${dr('other_income_including_interest')}`],['core_income_tax',`=D13*${dr('effective_tax_rate')}`],['core_income','=D13-D14'],['core_income_per_diluted_share_proxy',`=D15/${dr('diluted_shares')}`]];
 const mr={};defs.forEach(([n,f],i)=>{const r=i+7;mr[n]=r;model.getRange(`C${r}`).values=[[title(n)]];formula(model,`D${r}`,f);if(d.actual.metrics[n]!=null)model.getRange(`E${r}`).values=[[d.actual.metrics[n]]];});money(model,`D7:E${defs.length+6}`);if(mr.core_income_per_diluted_share_proxy)model.getRange(`D${mr.core_income_per_diluted_share_proxy}:E${mr.core_income_per_diluted_share_proxy}`).setNumberFormat('$0.00');if(mr.diluted_eps)model.getRange(`D${mr.diluted_eps}:E${mr.diluted_eps}`).setNumberFormat('$0.00');
 model.getRange('C22').values=[['Forecasts are analyst estimates, not the company’s official budget.']];model.getRange('C24').values=[[company==='PG'?'Cash flow uses a conversion assumption; it is not a full working-capital schedule.':'Per-share proxy excludes preferred / participating-security adjustments; it is not reported core EPS.']];
 const fc=sh['Forecast Comparison'];heading(fc,`${company} | Frozen forecasts vs actual`);header(fc,'C6:I6',['Information available','Case','Forecast revenue','Forecast profit','Actual profit','Actual less forecast','Variance % of forecast']);
 d.forecasts.forEach((f,i)=>{const r=i+7;fc.getRange(`C${r}:G${r}`).values=[[f.label,title(f.case),f.metrics[revenue],f.metrics[profit],d.actual.metrics[profit]]];formula(fc,`H${r}`,`=G${r}-F${r}`);formula(fc,`I${r}`,`=H${r}/ABS(F${r})`);});money(fc,'E7:H18');fc.getRange('I7:I18').setNumberFormat(PCT);signs(fc,'H7:H18');fc.getRange('C6:C18').format.columnWidth=35;
 fc.getRange('C21').values=[['These forecasts were frozen before actuals entered the model; rerun workflow to create a new vintage.']];
 const sum=sh.Summary;heading(sum,`${company==='PG'?'P&G':'Travelers'} | Scenario review`);sum.tabColor=brand;
 header(sum,'C5:F5',['Apr–Jun 2026','Actual','May base forecast','Actual less forecast']);
 [revenue,profit].forEach((m,i)=>{let r=6+i;sum.getRange(`C${r}:E${r}`).values=[[title(m),d.actual.metrics[m],d.forecasts[10].metrics[m]]];formula(sum,`F${r}`,`=D${r}-E${r}`);});money(sum,'D6:F7');signs(sum,'F6:F7');
 header(sum,'C10:G10',['Forecast vintage','Bear profit','Base profit','Bull profit','Actual profit']);Object.entries(d.runs).forEach(([v],i)=>{let r=i+11;sum.getRange(`C${r}`).values=[[d.forecasts.find(f=>f.vintage===v).label]];for(let j=0;j<3;j++)formula(sum,`${col(j+3)}${r}`,`='Forecast Comparison'!F${7+i*3+j}`);});sum.getRange('G11:G14').values=[[d.actual.metrics[profit]]];money(sum,'D11:G14');
 const chart=sum.charts.add('line',sum.getRange('C10:G14'));chart.setPosition('H5','M21');chart.title='Profit by information date';chart.titleTextStyle.fontSize=16;chart.titleTextStyle.typeface='Arial';chart.legend={position:'bottom',textStyle:{typeface:'Arial',fontSize:12}};chart.xAxis={axisType:'textAxis',textStyle:{fontSize:11,typeface:'Arial'}};chart.yAxis={numberFormatCode:'$#,##0"M"',numberFormatSourceLinked:false,textStyle:{fontSize:12,typeface:'Arial'}};['#BD2939',brand,'#16713E','#606870'].forEach((c,i)=>{chart.series.items[i].line={fill:c,width:2,style:i===3?'dashed':'solid'};});
 sum.getRange('C17').values=[['Quarter-start cutoff: 31 Mar 2026']];sum.getRange('C18').values=[['Mid-quarter cutoff: 15 May 2026']];sum.getRange('C20').values=[['Retrospective reconstruction using publication-date controls.']];sum.getRange('C22').values=[['Compare March and May history-only cases to isolate newly released financial information.']];
 sum.getRange('D11:F14').format.font={name:'Arial',size:12,color:'#111111'};
 const vd=sh['Variance Drivers'];heading(vd,`${company} | Why actual profit differed`);header(vd,'C5:F5',['Driver','May base assumption','Observed driver','Profit contribution']);
 d.actual_bridge.forEach((r,i)=>{let row=i+6;vd.getRange(`C${row}:F${row}`).values=[[title(r.driver),d.forecasts[10].drivers[r.driver]??null,d.actual_drivers[r.driver]??null,r.profit_change]];const info=d.runs.mid_market.assumptions.find(a=>a.driver===r.driver);if(info)vd.getRange(`D${row}:E${row}`).setNumberFormat(fmt(info.unit));});money(vd,`F6:F${5+d.actual_bridge.length}`);signs(vd,`F6:F${5+d.actual_bridge.length}`);
 const vr=7+d.actual_bridge.length;vd.getRange(`C${vr}`).values=[['Total actual less May base profit']];formula(vd,`F${vr}`,`=SUM(F6:F${5+d.actual_bridge.length})`);money(vd,`F${vr}`);vd.getRange(`C${vr+2}`).values=[['Sequential substitution in the displayed order; interactions are allocated to the later driver.']];
 const rc=sh['Research Changes'];heading(rc,`${company} | What research changed`);header(rc,'C5:H5',['Window / case','Driver','History assumption','Research assumption','Change','Reason from Scenario agent']);
 let rr=6;for(const window of ['pre','mid']){const ctrl=d.runs[window+'_history'].assumptions,updated=d.runs[window+'_market'].assumptions;for(const item of updated){const prev=ctrl.find(r=>r.driver===item.driver);const changed=['bear','base','bull'].filter(c=>item[c]!==prev[c]);for(const cas of (changed.length?changed:['base'])){rc.getRange(`C${rr}:F${rr}`).values=[[(window==='pre'?'March':'May')+' / '+cas,title(item.driver),prev[cas],item[cas]]];formula(rc,`G${rr}`,item.unit==='decimal'?`=(F${rr}-E${rr})*100`:`=F${rr}-E${rr}`);rc.getRange(`E${rr}:G${rr}`).setNumberFormat(fmt(item.unit));if(item.unit==='decimal')rc.getRange(`G${rr}`).setNumberFormat('0.0" pp";(0.0" pp");"–"');rc.getRange(`H${rr}`).values=[[changed.length?item.basis:item.basis.split(/(?<=[.!?])\s+(?=[A-Z])/).slice(0,2).join(' ')]];rr++;}}}
 rc.getRange(`C6:D${rr}`).format.columnWidth=31;rc.getRange(`H5:H${rr}`).format.columnWidth=95;rc.getRange(`H6:H${rr}`).format.wrapText=true;rc.getRange(`C6:H${rr}`).format.rowHeight=92;for(let n=6;n<rr;n++){if(String(rc.getRange(`H${n}`).values[0][0]).length>390)rc.getRange(`C${n}:H${n}`).format.rowHeight=170;}rc.freezePanes.freezeRows(5);
 model.getRange('G6:H8').values=[['Comparison','Profit'],['Selected case',null],['Actual',null]];formula(model,'H7',`=D${mr[profit]}`);formula(model,'H8',`=E${mr[profit]}`);money(model,'H7:H8');const mc=model.charts.add('bar',model.getRange('G6:H8'));mc.setPosition('G10','K21');mc.title='Selected profit vs actual';mc.hasLegend=false;mc.yAxis={numberFormatCode:'$#,##0"M"',numberFormatSourceLinked:false};mc.series.items[0].fill=brand;
 const health=sh['Financial Health'];heading(health,`${company} | Earlier-quarter financial review`);
 header(health,'C5:F5',['Jan–Mar metric','2026','2025','Year-on-year']);d.previous_quarter_diagnostics.forEach((r,i)=>{let n=i+6;health.getRange(`C${n}:E${n}`).values=[[title(r.metric),r.previous_quarter,r.prior_year_same_quarter]];formula(health,`F${n}`,`=D${n}/E${n}-1`);});money(health,'D6:E8');health.getRange('F6:F8').setNumberFormat(PCT);
 header(health,'C11:E11',['Balance sheet item','31 Mar 2026','31 Dec 2025']);const bmetrics=[...new Set(d.balance_history.filter(r=>r.period_end==='2026-03-31').map(r=>r.metric))];bmetrics.forEach((m,i)=>{const row=i+12;health.getRange(`C${row}`).values=[[title(m)]];for(const [p,c] of [['2026-03-31','D'],['2025-12-31','E']]){const x=d.balance_history.find(r=>r.metric===m&&r.period_end===p);if(x)health.getRange(`${c}${row}`).values=[[x.value]];}});money(health,'D12:E18');
 health.getRange('C21').values=[[company==='PG'?'Review cash generation alongside debt and capex; earnings alone do not establish liquidity.':'Insurance cash and equity are context, not a substitute for reserves, asset liquidity or statutory capital.']];health.getRange('C23').values=[['March results were published in April: available to May scenarios only.']];
 const e=sh['Market Evidence'];heading(e,`${company} | Evidence and proposed implications`);const evidence=JSON.parse(await fs.readFile(path.join(ROOT,'data/research/market_evidence.json'),'utf8')).records.filter(r=>r.company===company&&!r.excluded_from_model);header(e,'C5:H5',['ID','Published','Evidence','Driver implication','Proposed adjustment — before QA','Source']);
 evidence.forEach((r,i)=>e.getRange(`C${i+6}:H${i+6}`).values=[[r.id,r.published_at,r.factual_datapoint,r.rationale,r.suggested_adjustment_analyst_judgment,r.source_url]]);e.getRange('C5:C20').format.columnWidth=10;e.getRange('D5:D20').format.columnWidth=14;e.getRange('E5:H20').format.columnWidth=48;e.getRange('E6:H15').format.wrapText=true;e.getRange('C6:H15').format.rowHeight=100;e.freezePanes.freezeRows(5);
 const ck=sh['Sources and Checks'];heading(ck,`${company} | Sources and model checks`);header(ck,'C5:F5',['Source','Published','Latest period covered','Official release']);const sources=[...new Map([...d.history].sort((a,b)=>a.period_end.localeCompare(b.period_end)).map(r=>[r.source_id,r])).values()];sources.forEach((r,i)=>ck.getRange(`C${i+6}:F${i+6}`).values=[[r.source_id,r.publication_date,r.period_end,r.source_url]]);ck.getRange('F6:F18').format.columnWidth=95;
 const cr=19;header(ck,`C${cr}:E${cr}`,['Check','Difference','Tolerance']);formula(ck,'D20',`='Scenario Model'!D${mr[profit]}-${d.forecasts[10].metrics[profit]}`);ck.getRange('C20').values=[['Initial May base model vs frozen engine']];ck.getRange('E20').values=[[0.000001]];ck.getRange('D20:E20').setNumberFormat('0.000000');ck.getRange('D20').conditionalFormats.add('expression',{formula:'ABS(D20)>E20',format:{font:{color:'#BD2939'},fill:'#FCE4D6'}});
 ck.getRange('C22').values=[['This comparison changes when you edit assumptions; it checks the supplied initial model only.']];ck.getRange('C24').values=[['Source values are USD millions unless labelled per share, ratio or shares.']];ck.getRange('C26').values=[['Each historical value retains a source mapping in the accompanying CSV.']];
 const parity=[];
 for(let i=0;i<cases.length;i++){
  a.getRange('D4').values=[[cases[i]]];wb.recalculate();
  for(const [n] of defs){const val=model.getRange(`D${mr[n]}`).values[0][0],want=d.forecasts[i].metrics[n];if(typeof val!=='number'||!Number.isFinite(val)||Math.abs(val-want)>1e-5)throw new Error(`${company} ${cases[i]} ${n} parity: ${val} != ${want}`);parity.push({case:cases[i],metric:n,difference:val-want});}
 }
 a.getRange('D4').values=[[cases[10]]];wb.recalculate();
 const initial=model.getRange(`D${mr[profit]}`).values[0][0],expected=d.forecasts[10].metrics[profit],sensitivities=[];
 for(const driver of driverNames){const testCell=`${driverCol[driver]}34`,before=a.getRange(testCell).values[0][0];a.getRange(testCell).values=[[before+.01]];wb.recalculate();const vals=defs.map(([n])=>model.getRange(`D${mr[n]}`).values[0][0]);const changed=vals.some((v,i)=>Math.abs(v-d.forecasts[10].metrics[defs[i][0]])>1e-10);if(!changed)throw new Error('Driver does not propagate: '+driver);sensitivities.push({driver,changed});a.getRange(testCell).values=[[before]];wb.recalculate();}
 for(const s of Object.values(sh)){const vals=s.getUsedRange().values;for(const row of vals)for(const val of row)if(typeof val==='string'&&/^#(REF!|DIV\/0!|VALUE!|NAME\?|NUM!|N\/A)/.test(val))throw new Error('Formula error '+s.name+': '+val);}
 const inspections=[];for(const s of Object.values(sh)){inspections.push(await wb.inspect({kind:'region',sheetId:s.name,range:'C2:J20',maxChars:1400}));const preview=await wb.render({sheetName:s.name,headers:false,range:s.name==='Research Changes'?`C2:H${rr}`:s.name==='Summary'?'C2:M24':s.name==='Assumptions'?'C2:O36':s.name==='Historical Financials'?`C2:${col(periods.length+2)}${metrics.length+6}`:s.name==='Market Evidence'?'C2:H16':s.name==='Sources and Checks'?'C2:F27':s.name==='Scenario Model'?'C2:K26':'C2:J26',scale:1.4,format:'png'});await fs.mkdir(path.join(OUT,'screenshots',company),{recursive:true});await fs.writeFile(path.join(OUT,'screenshots',company,s.name.replaceAll(' ','_')+'.png'),new Uint8Array(await preview.arrayBuffer()));}
 const scan=await wb.inspect({kind:'match',searchTerm:'#REF!|#DIV/0!|#VALUE!|#NAME\\?|#NUM!|#N/A',options:{useRegex:true,maxResults:100},maxChars:3000});
 await fs.writeFile(path.join(OUT,`${company}_workbook_verification.json`),JSON.stringify({initial,expected,parity,sensitivities,formula_scan:scan,inspections},null,2));
 const file=await SpreadsheetFile.exportXlsx(wb);await file.save(path.join(OUT,`${company}_Financial_Scenarios.xlsx`));console.log(company,'exported; parity + live sensitivity verified');
}
